import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AboutLayout({ children }) {
  return (
    <div>
      <nav className="">
        <ul className="flex gap-5 mb-2">
          <li>
            <Link href={"/about/mission"}>Mission</Link>
          </li>
          <li>
            {" "}
            <Link href={"/about/vission"}> Vission</Link>
          </li>
        </ul>
        <hr />
      </nav>
      <div className="pt-5 ">
      {children}
      </div>
    </div>
  );
}
